name: LiePRing
version: 1.9.1
date: 2018-10-07
description: |
    Database and algorithms for Lie p-rings

authors:
    - name: Michael Vaughan-Lee
      url: http://users.ox.ac.uk/~vlee
    - name: Bettina Eick
      url: http://www.icm.tu-bs.de/~beick

maintainers:
    - name: Michael Vaughan-Lee
      url: http://users.ox.ac.uk/~vlee
    - name: Bettina Eick
      url: http://www.icm.tu-bs.de/~beick

GAP: "4.8"

needed-pkgs:
    - name: "LieRing"
      version: ">=2.1"
      url: "http://www.science.unitn.it/~degraaf/liering.html"

www: https://gap-packages.github.io/liepring/
readme: README.md
packageinfo: https://gap-packages.github.io/liepring/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/liepring/releases/download/v1.9.1/liepring-1.9.1.tar.gz

abstract: |

status: accepted
doc-html: htm/chapters.htm
doc-pdf: doc/manual.pdf
