name: LiePRing
version: "2.9"
license: "GPL-2.0-or-later"
date: 2024-04-29
description: |
    Database and algorithms for Lie p-rings

authors:
    - name: Bettina Eick
      url: http://www.iaa.tu-bs.de/beick
    - name: Michael Vaughan-Lee
      url: http://users.ox.ac.uk/~vlee

maintainers:
    - name: Bettina Eick
      url: http://www.iaa.tu-bs.de/beick
    - name: Michael Vaughan-Lee
      url: http://users.ox.ac.uk/~vlee

GAP: "4.8"

needed-pkgs:
    - name: "LieRing"
      version: ">=2.1"
      url: "https://gap-packages.github.io/liering/"

suggested-pkgs:
    - name: "Singular"
      version: ">=10"
      url: "https://gap-packages.github.io/singular/"

www: https://gap-packages.github.io/liepring/
readme: README.md
packageinfo: https://gap-packages.github.io/liepring/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/liepring/releases/download/v2.9/liepring-2.9.tar.gz

abstract: |

status: accepted
doc-html: htm/chapters.htm
doc-pdf: doc/manual.pdf
keywords: |
    , , .
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>EV24</span>]   <b class='BibAuthor'>Eick, B. and Vaughan-Lee, M.</b>,
     <i class='BibTitle'>LiePRing, Database and algorithms for Lie p-rings,
             Version 2.9</i>
     (<span class='BibYear'>2024</span>)<br />
    (<span class='BibNote'>GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/liepring/">https://gap-packages.github.io/liepring/</a></span>.
    </p>
    

bibtex: |
    @misc{ LiePRing,
      author =           {Eick, B. and Vaughan\texttt{\symbol{45}}Lee, M.},
      title =            {{LiePRing},    Database   and   algorithms   for   Lie
                          p\texttt{\symbol{45}}rings, {V}ersion 2.9},
      month =            {Apr},
      year =             {2024},
      note =             {GAP package},
      howpublished =     {\href       {https://gap-packages.github.io/liepring/}
                          {\texttt{https://gap\texttt{\symbol{45}}packages.github.io/}\discretionary
                          {}{}{}\texttt{liepring/}}},
      keywords =         {; ;},
      printedkey =       {EV24}
    }

