name: LiePRing
version: 2.8
date: 2022-10-21
description: |
    Database and algorithms for Lie p-rings

authors:
    - name: Bettina Eick
      url: http://www.iaa.tu-bs.de/beick
    - name: Michael Vaughan-Lee
      url: http://users.ox.ac.uk/~vlee

maintainers:
    - name: Bettina Eick
      url: http://www.iaa.tu-bs.de/beick
    - name: Michael Vaughan-Lee
      url: http://users.ox.ac.uk/~vlee

GAP: "4.8"

needed-pkgs:
    - name: "LieRing"
      version: ">=2.1"
      url: "https://gap-packages.github.io/liering/"
    - name: "Singular"
      version: ">=10"
      url: "https://gap-packages.github.io/singular/"

www: https://gap-packages.github.io/liepring/
readme: README.md
packageinfo: https://gap-packages.github.io/liepring/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/liepring/releases/download/v2.8/liepring-2.8.tar.gz

abstract: |

status: accepted
doc-html: htm/chapters.htm
doc-pdf: doc/manual.pdf
